#!/bin/sh

while read -r local_ref _local_sha _remote_ref _remote_sha
do
  case "$local_ref" in
    refs/heads/*)
      branch=${local_ref#refs/heads/}
      git ar validate-branch --branch "$branch" || exit $?
      ;;
  esac
done

exit 0
